-- ============================================
-- ADD ROADMAP_JSON COLUMN TO COURSE_PACKS TABLE
-- Migration to add JSONB field for storing complete roadmap data
-- ============================================

-- Add roadmap_json column if it doesn't exist
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 
    FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'course_packs' 
    AND column_name = 'roadmap_json'
  ) THEN
    ALTER TABLE public.course_packs 
    ADD COLUMN roadmap_json JSONB;
    
    COMMENT ON COLUMN public.course_packs.roadmap_json IS 
    'Complete topic session JSON generated by FinalTopicGen.py, including subskills, diagnostic questions, learning modules, and final quiz';
  END IF;
END $$;

-- Create index on roadmap_json for faster queries
CREATE INDEX IF NOT EXISTS idx_course_packs_roadmap_json 
ON public.course_packs USING GIN (roadmap_json);

-- Add comment to explain the structure
COMMENT ON COLUMN public.course_packs.roadmap_json IS 
'JSONB structure: {
  "course_pack_id": "course_xxxxx",
  "topic_session": {
    "topic_id": "topic_001",
    "title": "Course Title",
    "state": "diagnostic|learning|final|completed",
    "subskills": [{
      "subskill_id": "string",
      "name": "string",
      "mastery": 0.0,
      "evidence_chunk_ids": ["string"]
    }],
    "diagnostic": {
      "quiz_id": "string",
      "questions": [...],
      "submission": {...}
    },
    "learning_session": {
      "active_modules": [...]
    },
    "final_quiz": {
      "quiz_id": "string",
      "questions": [...],
      "submission": {...}
    },
    "completion": {
      "status": "not_started|in_progress|completed",
      "completed_at": "ISO timestamp"
    }
  }
}';
